Create task list
Guilherme-BS/todo-list pull request #1
Opened 2022-03-30 21:49 UTC by Guilherme-BS

##Description
> implement functionality to the add button, add the tasks in the Tasks remaining part##Changes 
before:
![Captura de tela de 2022-03-30 17-37-40](https://user-images.githubusercontent.com/73261443/160936590-6a941385-03a8-432b-88b5-f18a7b01d6ba.png)

after:
![Captura de tela de 2022-03-30 17-38-14](https://user-images.githubusercontent.com/73261443/160936622-f41777e1-ae4c-40d5-b25c-3d915d243c51.png)

![Captura de tela de 2022-03-30 17-40-44](https://user-images.githubusercontent.com/73261443/160936734-e41b7b24-7e88-4399-911d-8ad1b39c43b1.png)

2022-03-31 15:42 UTC, marco-souza reviewed
@Guilherme-BS bom trabalho!  🎉🎉

Parece que ta funcionando, mas tem algumas coisas que não seguem os padroes html, como o uso do `li`. Temos sempre que ter em mente que react é so uma camada acima do HTML, mas as boas praticas aprendidas são quase as mesmas.

Sei que parte do código já estava assim quando vc chegou, mas não tenha medo de alterá-lo. Código é feito pra jogar fora.

Deixei alguns links para estudo, separa um tempo pra ler eles com calma :)

Outra coisa **importante** é marcar a pessoa os reviewer no seu PR, pois assim seremos notificados que vc precisa de review.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/4452113/161095173-8a36f7f6-4a7e-40ba-906f-1c7c875dc1e3.png">

2022-03-31 15:42 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +function AddItemForm(props: any) {
Não podemos usar o type `any`, senao é o mesmo de não usar typescript.

Recomendo:
- criar uma interface para suas Props
- dar o spread(abertura) dos argumentos na assinatura da função

```suggestion
interface Props {
  // sua implementação aqui
}

function AddItemForm({ setDescription, description }: Props) {
```

Links para estudo:
- https://www.typescriptlang.org/docs/handbook/interfaces.html
- https://www.pluralsight.com/guides/defining-props-in-react-function-component-with-typescript

2022-03-31 15:42 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +  const [captureInput, setCaptureInput] = useState<string>();
Uma boa pratica quando usamos `useState` é **sempre** colocar um valor inicial.
No caso, o valor inicial de uma string é `''`

2022-03-31 15:42 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +    listDescription.push(captureInput);
Estamos usando o spread operator errado.
- https://www.samanthaming.com/tidbits/87-5-ways-to-append-item-to-array/

Recomendo:
- joga todos os items anteriores
- adiciona o novo item no final

```suggestion
    const listDescription = [
      ...description,
      captureInput,
    ];
```

2022-03-31 15:42 UTC, marco-souza commented on src/App.tsx
> +  const [description, setDescription] = useState([]);
Não me parece um bom nome. Estamos falando de tasks (tarefas) e o nome da variavel é `description` (descrição, no singular).

Recomendo repensar esses nomes pra ficar mais claro a sua lógica.

2022-03-31 15:42 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +  const handleInputText = () => {
Quando lidamos com onSubmit, precisamos pegar o evento e dar `preventDefault`.
Ah, seria bom colocar um type no evento também

- https://reactjs.org/docs/forms.html

2022-03-31 15:42 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +        value={captureInput}
`captureInput` nao ta um bom nome também.

Que vc acha de `inputValue`, ou `taskInputValue`?

2022-03-31 15:42 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +  const handleInputText = () => {
Se a gente der 'enter' ao inves de clicar no botão, sua pagina vai recarregar e perder os dados salvos

2022-03-31 15:42 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +        type="button"
dentro de form, o `type` correto desse botao seria "submit"
```suggestion
        type="submit"
```

2022-03-31 15:42 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +        onClick={handleInputText}
Se usamos o `onSubmit` no form, não tem necessidade de definir um onClick aqui. Pode remover.

2022-03-31 15:42 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +  const listName = description.map((name: string) => <ListModel name={name} />);
No react, temos que usar **sempre** a props `key` quando estivermos montando uma lista de elementos.

- https://reactjs.org/docs/lists-and-keys.html

2022-03-31 15:42 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +  const { description } = props;
Mesmo comentario das props la de cima

2022-03-31 15:42 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +        <li className="todo stack-small">{listName}</li>
Não podemos colocar esse `li` aqui. 

No html, li significa `list item`. Temos que ter um `li` para cada items, e não um com todos os items dentro. Faz sentido?

O correto seria so colocar a lista e mover o `li` para dentro do ``ListModel`.
```suggestion
        {listName}
```

2022-03-31 15:42 UTC, marco-souza commented on src/components/TaskItem.tsx
> +function ListModel(props: any) {
Nome desse componente não bate com o nome do arquivo. 

Recomendo sempre ter o mesmo nome do arquivo no componente que será o export padrão (`export default`)

2022-03-31 15:42 UTC, marco-souza commented on src/components/TaskItem.tsx
> +  const { name } = props;
Mesmo esquema do props comentado acima.

2022-03-31 15:42 UTC, marco-souza commented on src/components/TaskItem.tsx
> +    <>
O `li` deveria vir aqui

2022-03-31 15:42 UTC, marco-souza commented on src/components/TaskItem.tsx
> +        <input id="todo-0" type="checkbox" />
Como teremos um componente desse pra cada item da lista, não podemos usar o mesmo `id`, por a ideia do `id` é ser um **identificador unico** dentro do seu html.

Recomendo ou tirar o id, ou fazer um id dinâmico, baseado nos dados do item que ele representa

2022-03-31 15:48 UTC, marco-souza commented
Ah, outro ponto importante é o padrão dos commits. Recomendo ler nossa documentação de praticas de git

https://www.notion.so/Git-Guidelines-1281dded381c40e082b79d3d28c2cc8a#479d7b037d0e4b6da69b84c98962af64

2022-03-31 22:47 UTC, vzsoares reviewed
acho q vc resolveu bem o que o marco apontou . fica msm só essas 2 coisinhas que vi

2022-03-31 22:47 UTC, vzsoares commented on src/components/TaskDashboard.tsx
> +          <TaskItem key={name} name={name} />
talvez pudesse usar outro atributo no KEY para ser mais unico! (e se tiver duas tarefas iguais?...)

2022-03-31 22:47 UTC, vzsoares commented on src/components/TaskItem.tsx
> +    <li className="todo-stack-small">
esse  li  no react tmb creio q deva ter KEY

2022-04-01 11:25 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +          <TaskItem key={name} name={name} />
É um bom ponto. No momento não temos um identificador unico para os items, mas o key poderia ser algo tipo `${name}-${index}`.

Usar index como parte da `key` não é recomendável, pois o elemento pode mudar de posição, mas ainda sim ser o mesmo elemento, dificultando a vida do react na hora.

Enfim, para essa aplicação nao é um problema, mas em aplicações profissionais, teremos que usar sempre identificadores unicos

2022-04-01 11:26 UTC, marco-souza commented on src/components/TaskItem.tsx
> +    <li className="todo-stack-small">
Nesse não, a key vai no componente da lista, que no caso é o `TaskItem`. Como o `li` está dentro do componente, ele não precisa de key

2022-04-01 11:38 UTC, marco-souza commented on src/App.tsx
> +  console.log(taskList);
vamos evitar `console.log` nas aplicaçoes. Geralmente ele só é usado para debuggar codigo

2022-04-01 11:38 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +interface ListStateType {
Por padrao, quando estamos criando interfaces de props, elas começam com o nome do componente e terminam com o sufixo `Props`.
```suggestion
interface AddItemFormProps {
```

2022-04-01 11:38 UTC, marco-souza commented on src/components/AddItemForm.tsx
> +  const handleInputText = (e: React.FormEvent<HTMLFormElement>) => {
Acho que o nome dessa função mudou né? Ela não lida com evento de input text, mas sim o onSubmit.
```suggestion
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
```

2022-04-01 11:38 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +        {taskList.map((name: string) => (
Não tem nada errado aqui, mas uma dica é que não precisamos informar o tipo sempre, o TypeScript é capaz de inferir tipos baseado nas operacões.

nesse caso, por estarmos usando um **map numa lista de string**, ele sabe que `name` é uma string, sem vc precisar de informar, por ser a variavel que guarda um valor da lista (string).

Nesse caso podemos remover o tipo se quiser:
```suggestion
        {taskList.map((name) => (
```

2022-04-01 11:38 UTC, marco-souza commented on src/components/TaskItem.tsx
> +interface ItemName {
Nome tbm esta fora do padrao

2022-04-01 11:38 UTC, marco-souza commented on src/components/TaskItem.tsx
> +export default function TaskItem({ name, key }: ItemName) {
a props key é especial, não podemos usa-la como uma variavel, pois todo componente aceita `key`, mesmo que não esteja presente me suas props.

Recomendo mudar para `id` para evitar confusão.

2022-04-01 11:38 UTC, marco-souza commented on src/components/TaskItem.tsx
> +        <input id={key} type="checkbox" />
esse ID é realmente necessário? Se não for, recomendo só removê-lo. não tem um motivo prático no react para usar `id`. Isso vai ser mais usado quando formos falar de testes automatizados.

2022-04-01 11:38 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +          <TaskItem key={name} name={name} />
links para estudo:
- https://www.youtube.com/watch?v=ZKTaOoNCAcg
- https://www.youtube.com/watch?v=JPr8_RZp284

2022-04-01 11:38 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +interface ListType {
Fora do padrao de nome

2022-04-01 11:48 UTC, frattezi commented on src/components/TaskItem.tsx
> +          save
Os dois buttons poderiam seguir o mesmo padrão de escrita

2022-04-04 20:19 UTC, frattezi approved these changes
Acredito que está ok, vou deixar comentários posteriores no próximo PR

2022-04-04 20:19 UTC, frattezi commented on src/App.tsx
> +  console.log(taskList);
Console log

2022-04-04 20:19 UTC, frattezi commented on src/App.tsx
> +  const [taskList, setTaskList] = useState<string[]>([]);
task list é uma lista de strings ou de tasks?

2022-04-04 20:19 UTC, frattezi commented on src/App.tsx
> +  const [taskList, setTaskList] = useState<string[]>([]);
Vi que resolveu no outro Pr

2022-04-05 12:59 UTC, marco-souza requested changes
Tem uns comentários que foram marcados como resolvidos, mas na real não foram. Recomendo voltar olhar meus ultimos comentários.

Se tiver alguma divida me da um ping e podemos discutir

2022-04-05 12:59 UTC, marco-souza commented on src/components/TaskItem.tsx
> +interface ItemName {
Isso não foi resolvido

2022-04-05 12:59 UTC, marco-souza commented on src/components/TaskItem.tsx
> +        <input id={key} type="checkbox" />
Esse também não. não podemos usar o `key`, ele é especial

2022-04-05 12:59 UTC, marco-souza commented on src/components/TaskItem.tsx
> +  key: string;
Key tem que sair daqui

2022-04-05 12:59 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +        {taskList.map((name: string) => (
nao foi resolvido

2022-04-05 12:59 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +interface ListType {
tbm nao foi resolvido

2022-04-11 23:37 UTC, closed without merging