fea/ implement delete button functionality
Guilherme-BS/todo-list pull request #3
Opened 2022-04-12 18:14 UTC by Guilherme-BS

##Description 
>implement functionality to the delete button, when the delete button is clicked, I call a function that splices the array of names through the index and removes the task name from the list, then I make a copy of the array and save it.

2022-04-12 18:26 UTC, Filipe-barbosa commented on src/components/TaskDashboard.tsx
> +  deleteTask: (value: number) => void;
Dado que  o `TaskDashboardProps`, tem quase as mesmas propriedades da interface criada com o nome de taskItem props, com os tipos obrigatorios, e o index que nao esta presente nesta interface e usado no map, seria interessante reaproveitar os tipos ?

2022-04-12 18:59 UTC, Guilherme-BS commented on src/components/TaskDashboard.tsx
> +  deleteTask: (value: number) => void;
no caso o único tipo repetido e o da função delete task os outros são destintos

2022-04-12 20:26 UTC, vzsoares requested changes

2022-04-12 20:26 UTC, vzsoares commented on src/App.tsx
> +    taskList.splice(index, 1);
ao usar splice voce modifica o array original , e depois passa uma copia dele pro estado... acredito que nesse caso "filter" seria melhor alem de reduzir uma linha

2022-04-12 20:26 UTC, vzsoares commented on src/components/TaskItem.tsx
> +          onClick={() => deleteTask(index)}
se esta usando  index qual a necessidade de id?

2022-04-12 20:43 UTC, vzsoares commented on src/components/TaskItem.tsx
> +          onClick={() => deleteTask(index)}
so uma obs , falto dar deploy no ghpages tmb

2022-04-12 21:06 UTC, Guilherme-BS commented on src/components/TaskItem.tsx
> +          onClick={() => deleteTask(index)}
entendi nao

2022-04-12 21:09 UTC, vzsoares commented on src/components/TaskItem.tsx
> +          onClick={() => deleteTask(index)}
github pages ta na versao sem essa funcionalidade tendeu

2022-04-14 13:17 UTC, marco-souza requested changes

2022-04-14 13:17 UTC, marco-souza commented on src/App.tsx
> +    taskList.splice(index, 1);
E usando o filter nem precisamos de fazer o spread abaixo

2022-04-14 13:17 UTC, marco-souza commented on src/components/TaskItem.tsx
> +          Edit <span className="visually-hidden" />
Isso não deveria ser dinamico?

2022-04-14 13:17 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +            deleteTask={deleteTask}
Que tal juntar essas linhas e evitar passar o index?
```suggestion
            deleteTask={() => deleteTask(index)}
```

2022-04-14 13:17 UTC, marco-souza commented on src/components/TaskItem.tsx
>  }
Se seguir a sugestao acima, aqui ficaria
```suggestion
interface TaskItemProps {
  taskName: string;
  deleteTask: () => void;
}
```

2022-04-14 13:17 UTC, marco-souza commented on src/components/TaskItem.tsx
> +          onClick={() => deleteTask(index)}
Se seguir meu comment acima, aqui ficaria

```suggestion
          onClick={deleteTask}
```

Daria uma simplificada legal! 😁

2022-04-15 14:23 UTC, Guilherme-BS commented on src/App.tsx
> +    taskList.splice(index, 1);
conseguir resolver isso

2022-04-15 14:25 UTC, Guilherme-BS commented on src/components/TaskItem.tsx
> +          Edit <span className="visually-hidden" />
na versao do edit eu coloquei ele dinamico ta em uma branch diferente

2022-04-15 17:22 UTC, vzsoares requested changes

2022-04-15 17:22 UTC, vzsoares commented on src/App.tsx
> +    console.log(taskList);
👁

2022-04-15 17:22 UTC, vzsoares commented on src/components/TaskItem.tsx
> +  const [editando, setEditando] = useState<boolean>(false);
https://www.youtube.com/watch?v=HbvYeLxMKN8&ab_channel=BrunoBressam
(bricadeira viu)

2022-04-15 17:22 UTC, vzsoares commented on src/components/TaskItem.tsx
> +  const [inputEdit, setInputEdit] = useState<string>(taskName);
>  <sup></sup>"inputEdit" em ingles nao faz muito sentido , o certo seria "editInput" ou ate "editingInput"

2022-04-15 17:22 UTC, vzsoares commented on src/components/TaskItem.tsx
> +  };
como essa funçao é ultilizada apenas na [linha](https://github.com/Guilherme-BS/todo-list/pull/3/files#diff-d3ac101ffd80b9be0b7e83e7e20cbde310abc1bad67edb9dc5d6ab1ade55066aR41) 41 acho que poderia fazer um callback no proprio onClick

2022-04-15 17:22 UTC, vzsoares commented on src/components/TaskItem.tsx
> +        <button type="button" className="btn" onClick={togleEdit}>
> continuando comentario da linha [18](https://github.com/Guilherme-BS/todo-list/pull/3/files#diff-d3ac101ffd80b9be0b7e83e7e20cbde310abc1bad67edb9dc5d6ab1ade55066aR18)

ficando entao
```suggestion
        <button type="button" className="btn" onClick={() => setEditando(!editando)}>
```
podendo assim excluir funçao  togleEdit

2022-04-15 17:22 UTC, vzsoares commented on src/components/TaskItem.tsx
> +        )}
legal sua soluçao porem acabou modificando o layout original da aplicaçao , dai acho que seria melhor o @marco-souza dar uma olhada

2022-04-18 11:39 UTC, marco-souza commented on src/components/TaskItem.tsx
> +        )}
Sim, recomendo reutilizar os mesmos classNames aqui para reaproveitar os estilos existentes previamente

2022-04-18 11:40 UTC, marco-souza commented on src/components/TaskItem.tsx
> +          Edit <span className="visually-hidden" />
Saquel. Mas se ta em um branch diferente, pq ele foi editado aqui?

2022-04-18 11:41 UTC, marco-souza commented
@Guilherme-BS depois da uma conferida na descricao, ela ta ficando sem formatacao do markdown. Se nao tiver confortavel com markdown, tira um tempo pra estudar ele tbm

2022-04-18 11:45 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +        {taskList.map((task, index) => (
`index` esta sendo usado?

2022-04-18 11:45 UTC, marco-souza commented on src/components/TaskDashboard.tsx
> +        {taskList.map((task, index) => (
Se nao, podemos remover ele

2022-04-18 11:45 UTC, marco-souza commented on src/components/TaskItem.tsx
> +  const [editando, setEditando] = useState<boolean>(false);
Acho importante manter o c'odigo coeso. No caso a linguagem usada eh grande responsavel pela coesao.

Recomendo passar isso pra ingles.

2022-04-18 11:45 UTC, marco-souza commented on src/components/TaskItem.tsx
> +          <label className="todo-label" htmlFor="todo-0">
Nao acho que isso deferia ser uma label. Label sao relacionadas aos inputs. Como nao teremos input se nao tiver editando, eh melhor mudar isso. Talvez um `p` ou ate mesmo uma `div`

2022-04-18 18:14 UTC, Guilherme-BS commented on src/components/TaskItem.tsx
> +          Edit <span className="visually-hidden" />
fiz doideira aqui com abri uma branch pra fazer o edit e usei a mesma, vou apagar as alteracoes relacionadas ao edit nessa e fazer so na outra

2022-04-18 19:57 UTC, marco-souza approved these changes
A parte do delete ta show! Vi que antes vc tava mandando a parte do edit tbm, mas agora ta certinho 💪

Algumas dicas para os proximos:
- criar descriçoes melhores seguindo a formatação do Markdown
- Criar branchs e commits usando nossas [praticas de git](https://www.notion.so/Git-Guidelines-1281dded381c40e082b79d3d28c2cc8a#479d7b037d0e4b6da69b84c98962af64)

2022-04-18 19:58 UTC, marco-souza commented on src/components/TaskItem.tsx
> +  const [edit, setEdit] = useState<boolean>(false);
É bobagem, mas o nome correto dessa variavel seria `isEditing` (esta editando)
```suggestion
  const [isEditing, setIsEditing] = useState<boolean>(false);
```

2022-04-18 21:21 UTC, vzsoares approved these changes
show!
realmente só separar mais as mudanças nos commits e evitar force push

> separar os commit é bom por exemplo 
> ![image](https://user-images.githubusercontent.com/86134825/163879691-afc61389-f53a-4ee0-8f69-5f021cb7fdfd.png
)
> pq da pra separar por aqui na hora de revisar e ajuda bastante

2022-04-18 22:06 UTC, merged